CREATE TABLE IF NOT EXISTS Company(
	COMPANY_CODE VARCHAR(50) PRIMARY KEY,
	COMPANY_NAME VARCHAR(50)
	);

CREATE TABLE IF NOT EXISTS App_User(
	COMPANY_CODE VARCHAR(50),
	USER_ID VARCHAR(50) PRIMARY KEY,
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    AGE INT
	);