CREATE TABLE IF NOT EXISTS Company(
	COMPANY_CODE CHAR(6) PRIMARY KEY,
	COMPANY_NAME VARCHAR(255)
	);

CREATE TABLE IF NOT EXISTS App_User(
	COMPANY_CODE CHAR(6),
	USER_ID CHAR(6) PRIMARY KEY,
	FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    AGE INT,
	COMPANY_CODE CHAR(6) REFERENCES Company(COMPANY_CODE)
	);